#!/usr/bin/env python3
#
# daws is a version of the aws command that automatically adds and shows metadata
#

import sys
import os
import subprocess

from dvs_helpers import *

def do_s3(s3args):
    if s3args[0]=='cp' and not s3args[1].startswith('s3://') and s3args[2].startswith('s3://'):
        fn = s3args[1]
        print(f"{fn} SHA1=",end='',flush=True)
        hashes = hash_file(fn)
        print(hashes[HEXHASH])
    
if __name__ == "__main__":
    from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    clogging.add_argument(parser,loglevel_default='WARNING')
    parser.add_argument("cmd")
    parser.add_argument("args",nargs='*')
    args = parser.parse_args()
    clogging.setup(args.loglevel)

    if args.cmd=='s3':
	do_s3(args.args)
    
    subprocess.call(['aws',args.cmd,*args.args])
